### ISSUE TITLE
Small error in the `access-elements` docs

### ISSUE THREAD

**Issue by mabergerx** [jina-ai/docarray#123]
I was following the documentation over [here](https://docarray.jina.ai/fundamentals/documentarray/access-elements/), and saw that at the [Splitting by `.tags` section](https://docarray.jina.ai/fundamentals/documentarray/access-elements/#splitting-by-tags), the following method is used:

```python
rv = da.split(tag='category')
```

However, no such method exists. I figured that it has to be 

```python
rv = da.split_by_tag(tag='category')
```

So the documentation needs to be updated to reflect that :)

**Comment by JoanFM** [comment]
Thanks @mabergerx for the help! A PR is on the way
