### ISSUE TITLE
Creating document with blob data "drop" text data

### ISSUE THREAD

**Issue by josca42** [jina-ai/docarray#153]
As far as I can tell the below is not intended behaviour. If you initialise a docarray with both blob and text data then the text data is dropped.

```
d = Document(text="test")
d.text

>>> "test"
```

```
d = Document(text="test", blob=[1, 2, 3])
d.text

>>> ""
```

**Comment by hanxiao** [comment]
Each Document can contain only one type of content, one of `text`, `blob` or `tensor`. That means these three attributes are mutually exclusive. 

Docs: https://docarray.jina.ai/fundamentals/document/attribute/?highlight=exclusive#content-attributes

**Comment by josca42** [comment]
Ahh. My bad. Should have read the docs more thoroughly :-)
