### ISSUE TITLE
Add inplace parameter for DocArray operations

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/docarray#278]
Add parameter `inplace` for all operations that might modify Document and DocumentArray.
Default value is True for compatibility

**Comment by hanxiao** [comment]
hmm is this really needed? i'd like to here more rationale and API pseudo code before starting

**Comment by alaeddine-13** [comment]
Currently, in case you need to operate on a converted attribute without really modifying the Document, you need to first copy, convert and then use.

For example, suppose we want to send Docs with image URIs and only convert image uri to tensor when we want to embed (no need to index Docs with image tensors), you'd do:

```python
class Encoder(Executor):
    def encode(self, da: DocumentArray, **kwargs):
        for d in da:
            d.embedding = deepcopy.copy(d.load_uri_to_image_tensor())\
                                       .embed(model).embedding
```

The new API would be:

```python
class Encoder(Executor):
    def encode(self, da: DocumentArray, **kwargs):
        for d in da:
            d.embedding = d.load_uri_to_image_tensor(inplace=False)\
                                       .embed(model).embedding
```

The parameter `inplace=False` means returning a modified copy of the Document instead of modifying and returning the same reference

**Comment by hanxiao** [comment]
but this is too much, think about the type annotation and documentation you need to change.

**Comment by alaeddine-13** [comment]
We don't have to change the return type. We can keep returning the same reference in case inplace=True (by default) in order to keep the fluent interface and for compatibility. The discussed feature would only extend the behavior of some methods and we should only narrate the new behavior in case inplace=False

**Comment by alaeddine-13** [comment]
closing since this task is no more in plan
