### ISSUE TITLE
Document.to_json converts tags wrongly

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/docarray#287]
```python
from docarray import Document
print(Document(
    tags={'i': 1},
).to_json(exclude_none=True))
```
returns `{"id": "72ac6f45b342d065839464d56bec7af8", "tags": {"i": true}}`
it should return `{"id": "72ac6f45b342d065839464d56bec7af8", "tags": {"i": 1}}` instead

**Comment by davidbp** [comment]
I am not sure we can solve this

by adding in `pydantic_model`

```python
_ProtoValueType = Optional[Union[int, bool, float, str, list, dict]]
```

Then  the code from above prints
```python
{"id": "c801e02ecc274ce09f7ec4c8e5d20ff5", "tags": {"i": 1}}
```

But then we introduce the issue that

```python
d =Document(tags={'i': True})
print(d.to_json(exclude_none=True))

d =Document(tags={'i': False})
print(d.to_json(exclude_none=True))
```

prints 

```
{"id": "46e3c50762b8c0b1c0745d4b176f9ef2", "tags": {"i": 1}}
{"id": "c0b613146f3bbd38fd762958482cab31", "tags": {"i": 0}}
```

Any ideas on how to handle int 1/0 and True/False @hanxiao ?  At a first glance it seems 'in-decidable' from reading the variable in memory.

**Comment by hanxiao** [comment]
upstream? maybe post it to pydantic

**Comment by hanxiao** [comment]
i believe if you change the order inside union the result will also change. that's why i say it is an upstream issue

**Comment by JoanFM** [comment]
I agree with @hanxiao and I think there is very little one can do.

**Comment by davidbp** [comment]
https://github.com/samuelcolvin/pydantic/discussions/4018

**Comment by numb3r3** [comment]
Actually, we already discussed this issue before  https://github.com/jina-ai/docarray/issues/72#issuecomment-1018225292

**Comment by alaeddine-13** [comment]
closing this task since it's an upstream issue
