### ISSUE TITLE
Clarify the basic example of the documentation of GraphQL support of DocArray

### ISSUE THREAD

**Issue by DOling** [jina-ai/docarray#295]
**Describe your proposal**
I stumbled across your comprehensive documentation of the support of GraphQL of DocArrays. One little thing confused me when I first read it:
There is a second DocArray initialized in the basic example. I do not think that this is necessary to understand the GraphQL support of the DocArrays.
I would suggest deleting this section so as not to distract from the main point – GraphQL.

**Comment by DOling** [comment]
Thank you, hanxiao! I apologize for the inconvenience!

**Comment by hanxiao** [comment]
I think what happened in the docs is that I constructed `matches` in order to use it in the demo, but then I must be distracted by something else and forget about it. In the end, the demo just showed a very simple `.id` selection.

Let me revise this section.

**Comment by hanxiao** [comment]
fixed and rolled out https://docarray.jina.ai/advanced/graphql-support/
