### ISSUE TITLE
Allow fuzzy tag search

### ISSUE THREAD

**Issue by davidbp** [jina-ai/docarray#320]
Some users requested the capability to do fuzzy string matching at a tag level.

**Comment by JoanFM** [comment]
Please @davidbp, can u please develop the idea, what is the intented behavior

**Comment by davidbp** [comment]
Some users wanted to search in ‘uncleaned data’ with tags. Imagine the context where your users add information and this information is not selectable from a list of possible values. Then groups defined by tags become fuzzy/not clean. This makes filtering a problem, since categories might have to be either cleaned a-priory or search has to take this into account.

**Comment by davidbp** [comment]
Closing because this was deemed not rellevant.
