### ISSUE TITLE
Bug Report: DocumentArray Embedding Projector visualization FileNotFoundError

### ISSUE THREAD

**Issue by MikeTrizna** [jina-ai/docarray#34]
I'm not entirely sure what is causing this, but I keep getting the error `FileNotFoundError: [Errno 2] No such file or directory: {some long install path}/docarray/resources/embedding-projector/index.html.gz' when trying to run the minimal example from https://docarray.jina.ai/fundamentals/documentarray/visualization/#embedding-projector.

I first ran into it on Google Colab, after installing DocArray with `pip install "docarray[full]"` (Version 0.1.4). I then tried installing from source with `pip install git+https://github.com/jina-ai/docarray.git` (Version 0.1.5). This seemed to address that index.html.gz FileNotFound error, but then I got the message `You should see a webpage opened in your browser, if not, you may open http://localhost:35967/static/index.html?config=config.json manually`, which made me think it won't be possible in Colab (without additional tweaking).

I then tried to install on my local MacBook, using `pip install "docarray[full]"`, `pip install git+https://github.com/jina-ai/docarray.git`, and conda install, but simply couldn't get around the index.html.gz FileNotFoundError.

I was so excited to see the Tensorboard Embedding Projector working so seamlessly in the documentation, so hopefully this bug report helps get that working more universally.

**Comment by hanxiao** [comment]
Thanks for reporting, let me check

**Comment by hanxiao** [comment]
confirmed as a bug, will fix it now

**Comment by hanxiao** [comment]
hi, this is solved and released in 0.1.5, please do `pip install -U docarray`. thanks for reporting & closing this issue now. Further question can start with a new issue

**Comment by hanxiao** [comment]
okay i just realized there is a sub-quesiton in your issue: you were asking to run embedding projector inside Google colab, that is another thing tricky but should be doable, let me open a ticket for you. https://github.com/jina-ai/docarray/issues/38
