### ISSUE TITLE
Jina supports executors as 'docker//:container_name'  but docarray doesnt

### ISSUE THREAD

**Issue by amazingvince** [jina-ai/docarray#380]
Title says most of it but you cant use 'docker//:container_name'  as its not a supported schema. Would be nice to have for testing and closed env deployments.
Exact error: ValueError: unsupported scheme: docker

```
from docarray import Document, DocumentArray

da = DocumentArray([Document(text='hello')])
r = da.post('docker://container_name')

print(r.to_json())
```

**Comment by JoanFM** [comment]
Hello, @amazingvince,

This is not possible to work, what `da.post()` expects is a valid endpoint from a `Jina's Flow` gateway. `docker://...` is the syntax used by Jina to load Executors from docker images, but they do not make a valid `Jina Flow` gateway where to send Requests with `DocumentArrays`

Could you please send us the rationale from documentation that lead you to think this could work. This may help us improve our documentation.

**Comment by amazingvince** [comment]
I guess I am struggling to understand the difference between docker:// and jinahub+docker://. I looked at the mix-ins and post seems to create a jina flow and I dont understand why jinahub+docker:// would function but docker:// would not. I have not been able to use either yet because I am on windows. I am setting up an ubuntu env today so maybe it will make more sense once I get my hands dirty.

Starting on line 59 in post.py 
class postmixin
`        if _scheme.startswith('jinahub'):
            from jina import Flow

            f = Flow(quiet=True, prefetch=1).add(uses=standardized_host)
            with f:
                return f.post(
                    _on,
                    inputs=self,
                    show_progress=show_progress,
                    request_size=batch_size,
                    parameters=parameters,
                    **kwargs,
                )`
If flows can accept docker:// why could that not work here as well?

**Comment by amazingvince** [comment]
This is the documentation that confused me:
https://docarray.jina.ai/fundamentals/documentarray/post-external/
<html>
<body>


2. One of jinahub, jinahub+docker, jinhub+sandbox | Jina hub executor in source code, **Docker container**, sandbox
-- | --



</body>
</html>
