### ISSUE TITLE
Error: all input arrays must have the same shape

### ISSUE THREAD

**Issue by einfachluki** [jina-ai/docarray#39]
Unfortunately, when following your steps, i get the error:  "all input arrays must have the same shape"

**Comment by hanxiao** [comment]
> when following your steps,

could you elaborate it by copy-paste your code here, thanks

**Comment by einfachluki** [comment]
<img width="726" alt="Bildschirmfoto 2022-01-12 um 12 25 06" src="https://user-images.githubusercontent.com/8719545/149131543-ced9ef51-427c-48a9-9a92-359b015888b8.png">

**Comment by hanxiao** [comment]
based on the part of your code, I'm guessing your input images are not in the same shape, e.g. some are `256px x 256 px` some are arbitrary size images. And if I'm correct about it, you need to add a preprocessing step to resize the images. You can do it by:
```python
d = Document()
d.set_image_blob_shape(shape=(128, 128))
```

If you are working with DocumentArray as in README

```python
from docarray import Document

def preproc(d: Document):
    return (d.load_uri_to_image_blob()  # load
             .set_image_blob_shape(shape=(128, 128))  # <----- ADD to unify the shape
             .set_image_blob_normalization()  # normalize color 
             .set_image_blob_channel_axis(-1, 0))  # switch color axis for the pytorch model later

```

**Comment by einfachluki** [comment]
Thank you!
