### ISSUE TITLE
How to manage large quantity of filters with weaviate backend

### ISSUE THREAD

**Issue by vincetrep** [jina-ai/docarray#409]
Hello,

I am looking to manage a large set of filters for my search index, where some of them are represented with booleans such as the presence of allergens (gluten-free, soy-free, etc...) for food/recipe records.

Using docarray and weaviate backend.

As the docarray metadata is primarily stored with tags and then in weaviate columns, what would be the best recommendation to store those boolean values?

Option 1: 1 column per boolean. What would be the impact of having 80+ of those columns on index size?
Option 2: concatenated string of boolean values stored in one column <<allergens>> for instance. Would that work and what would be the recommended way to filter efficiently on this?
Other options?

Thanks for your help,

Vincent

**Comment by JoanFM** [comment]
Yes, we will close this issue for now. If you have some findings to share, you are welcome to share with community. Thanks!
