### ISSUE TITLE
Final result are not displayed 

### ISSUE THREAD

**Issue by einfachluki** [jina-ai/docarray#41]
The following lines of codes (as also shown in the documentation) are not displaying me any result matrix. 
The code only runs through without throwing any error but it does not display anything.

(DocumentArray(left_da[8].matches, copy=True)
    .apply(lambda d: d.set_image_blob_channel_axis(0, -1)
                      .set_image_blob_inv_normalization())
    .plot_image_sprites('result.png'))

**Comment by hanxiao** [comment]
could you elaborate which environment are you running? Jupyter notebook? google colan? IDE? python console? Python from terminal. It help me to understand what "display" means. Thanks

**Comment by einfachluki** [comment]
Im running it on Google Colab. With displaying I mean showing as output in the console, sorry

**Comment by hanxiao** [comment]
You code specify the destination of the image to a file, hence it is not write to colab cell
```python
.plot_image_sprites('result.png')
```

changing it to 
```python
.plot_image_sprites()
```

should do

**Comment by einfachluki** [comment]
Tried this already but these lines of code are only displaying me nine pictures of the "right_da"-dataset instead of:
1.) One benchmarking picture of the "left_da"-dataset and
2) the top nine best matching pictures of the "right_da"-dataset (as shown in the attached picture)
<img width="482" alt="Bildschirmfoto 2022-01-12 um 19 26 50" src="https://user-images.githubusercontent.com/8719545/149199993-8051783b-17f2-4295-a787-d224703ffd49.png">
