### ISSUE TITLE
jupyter cell output cluttered with empty output with unknown origin

### ISSUE THREAD

**Issue by eschmidt42** [jina-ai/docarray#426]
# The problem

`docarray` mapping functions in jupyter notebooks (VS Code and original jupyter) seem to produce empty output that is printed to the cell output. 

This leads to the cell output becoming extremely long and error messages etc very hard to locate.

The empty output for a short loop:
![empty-output](https://user-images.githubusercontent.com/11818904/177000041-e6d6da90-ad60-4509-9787-d041fa277d72.jpg)

The empty output seems to scale with the number of loop iterations.

# Attempted solutions

Read the documentation carefully (I'm new to `docarray` 😁  ). But didn't find a reference.

Set `show_progress = False` where possible (although apparently already the default). But unsurprisingly this didn't help.

# Minimal example to reproduce the behavior

* **OS**: Ubuntu 20.04
* **Python**: 3.9.0
* [Repo with example](https://github.com/eschmidt42/docarray-cell-output-issue)
  * [jupyter notebook](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/minimal-example.ipynb)
  * [requirements.txt](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/requirements.txt)
  * [pyproject.toml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/pyproject.toml)
  * [poetry.lock](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/poetry.lock)

Happy about any pointers! 😄

**Comment by JoanFM** [comment]
Hello @eschmidt42 ,

what version of DocArray are u using? I do not manage to reproduce the issue

**Comment by eschmidt42** [comment]
Hi @JoanFM ,

according to my [requirements.txt](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/requirements.txt) / [pyproject.toml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/pyproject.toml) that should be the most recent version 0.13.27.  

I originally installed via pip/poetry. Just also tested install via conda and get the same issue. The corresponding [environment.yaml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/environment.yml) is uploaded to the same repo.

Installing on my local machine (WSL2 & Ubuntu 20.04) using poetry, I can reproduce the empty cell output behavior.

**Comment by hanxiao** [comment]
I tried this mwu, but can't reproduce? could you give it a try?
```python
from docarray import DocumentArray
da = DocumentArray.empty(1000)
for d in da.map_batch(lambda x: x, batch_size=10):
    pass
```

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/2041322/177034343-e4bb30f5-8b00-478d-ae12-d496d7d2adb9.png">

**Comment by JoanFM** [comment]
I could not reproduce, I have the feeling that is not an issue with docarray but perhaps some specific jupyter configuration

**Comment by eschmidt42** [comment]
> I tried this mwu, but can't reproduce? could you give it a try?
> 
> ```python
> from docarray import DocumentArray
> da = DocumentArray.empty(1000)
> for d in da.map_batch(lambda x: x, batch_size=10):
>     pass
> ```
> 
> <img alt="image" width="1147" src="https://user-images.githubusercontent.com/2041322/177034343-e4bb30f5-8b00-478d-ae12-d496d7d2adb9.png">

This also works fine for me. Perhaps it's due to the `map` functions being called in `batch_func` somehow?

The entire code from the [linked notebook](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/minimal-example.ipynb):
```python
from docarray import Document, DocumentArray, dataclass
from docarray.typing import Image
from typing import List

# `!wget https://docarray.jina.ai/_images/apple1.png` 

uri = "apple1.png"

@dataclass
class Basket: # this is where the apples go
    images: List[Image] 


n_baskets = 10
n_items = 3 # all baskets have the same number of apples for simplicity

baskets = DocumentArray([
    Document(Basket(images= [uri for _ in range(n_items)]))
    for _ in range(n_baskets)
])

image_size = (64,64)

def img_func(d:Document): # tensor transforms here don't seem to generate the output
    return (d
    .set_image_tensor_shape(image_size)
    .set_image_tensor_normalization()
    .set_image_tensor_channel_axis(original_channel_axis=-1, new_channel_axis=0)
    )

def chunk_func(d:Document):   
    # iterating Basket.images 
    return DocumentArray(d.chunks[0].chunks.map(img_func)) # <= empty output generated here?

def batch_func(b:DocumentArray):
    # iterating Basket documents in batch
    return b.map(chunk_func) # <= empty output generated here?


for i, b in enumerate(baskets.map_batch(batch_func, batch_size=5)):
    images = [_d.tensors for _d in b]
```

**Comment by samsja** [comment]
Hey @eschmidt42 which version of jupyter are you using ?

**Comment by eschmidt42** [comment]
Hi @samsja ,

the [environment.yml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/environment.yml) says:
```yaml
  - jupyter=1.0.0=py39hf3d152e_7
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py39hf3d152e_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
```

I think to get the same env one could use:
* `git clone https://github.com/eschmidt42/docarray-cell-output-issue.git` (contains an [environment.yml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/environment.yml) and poetry files,
* cd into the new dir,
* conda: `conda env create -f environment.yml` or
* poetry (my default): `poetry install` with the [pyproject.toml](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/pyproject.toml) and [poetry.lock](https://github.com/eschmidt42/docarray-cell-output-issue/blob/main/poetry.lock) in your directory. 

Thank you all for looking at this! 😁
