### ISSUE TITLE
How to find by list? 

### ISSUE THREAD

**Issue by Pathos14489** [jina-ai/docarray#434]
So to explain my situation, I have a document array of documents where every document has a list under the tags attribute called TAGS which is a list of strings.

```python
r = doc_array.find({'tags__TAGS': {'$in': 'test'}})
```

^Gives me `TypeError: 'in <string>' requires string as left operand, not list`

```python
r = doc_array.find({'tags__TAGS': {'$in': ["test"]}})
```

^Results in zero results even on queries I know should have results.
I've tried both of these ways to query just for one tag to be in the array(even though I *want* to query for a whole list of tags to be present in the end, but I can figure that out if someone can help me figure this part out), and for each of them I get errors. 
 
I've also looked into how this is done on Mongo to be sure I was following the correct example since there's not exactly a lot of information about this in the documentation, but that led nowhere.

```python
r = doc_array.find({'tags__TAGS': 'test'})
```

`ValueError: Not a valid query. It should follow the format:`
`                    { <field1>: { <operator1>: <value1> }, ... }`
I feel like I'm just being dense and missing something obvious, but I also feel like I've tried everything that makes sense to me.

How am I supposed to be doing this? Does `$in` actually mean that the field has to be a single value that's checked against an array value? If so, is there like... a `$contains` or something that isn't documented?

**Comment by JoanFM** [comment]
Hey @Pathos14489,

Can you provide a minimum reproducible example of the documents you index. I think that the second query should be the correct one

**Comment by JoanFM** [comment]
This seems to be working on my end:

```python
from docarray import DocumentArray, Document

doc_array = DocumentArray()

doc_array.append(Document(tags={'TAGS': 'test'}))
doc_array.append(Document(tags={'TAGS': 'notest'}))
r = doc_array.find({'tags__TAGS': {'$in': ['test']}})

# r gets length of 1
```

I wonder if your `DocumentArray` is a `DocumentArray` of one of the backends or is a DocumentArray living in memory.

**Comment by JoanFM** [comment]
Hey @Pathos14489 is there any news about this?
