### ISSUE TITLE
bug(elastic): indexing using non str id, broke offset persistence consistency

### ISSUE THREAD

**Issue by alphinside** [jina-ai/docarray#435]
Hi, I found that executing this code 

```python
import logging
import sys
from docarray import DocumentArray,Document

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s : %(levelname)s : %(message)s",
    stream=sys.stdout,
)
da= DocumentArray(
    storage='elasticsearch',
    config={
        'n_dim': 3,
        'index_name': 'test-docarray',
        'columns': [('price', 'int')], 'distance': 'l2_norm'
    },
)

with da:
    da.extend(
        [
            Document(id=i,embedding=[i,i,i],price=i) for i in range(20)
        ]
    )

print(da[:,"id"])
print(da._offset2ids.ids)
```

will raise offset consistency issue when we execute it more than one times. The number of docs documented in offset2ids index will increase by 2 times.  The result of the `print(da._offset2ids.ids)` on the 2nd execution will look like this 

```
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

After further inspection, I think that the problem raises because we store the offset as blob and read the id from blob which will convert the id as str

```python
def _update_offset2ids_meta(self):
        """Update the offset2ids in elastic"""
        if self._client.indices.exists(index=self._index_name_offset2id):
            requests = [
                {
                    '_op_type': 'index',
                    '_id': offset_,  # note offset goes here because it's what we want to get by
                    '_index': self._index_name_offset2id,
                    'blob': f'{id_}',
                }  # id here
                for offset_, id_ in enumerate(self._offset2ids.ids)
            ]

def _get_offset2ids_meta(self) -> List:
        ...
        ids = [x['_source']['blob'] for x in resp['docs']]
```

thus when we provide int id at the beginning, it will be converted to str the next time we get it and not detected as unique by the logic at the `extend` function

**Comment by JoanFM** [comment]
Hey @alphinside,

This comes from a bad usage of DocArray, as you see here https://docarray.jina.ai/fundamentals/document/#document

Document ID is a string and therefore it should be given as a string.

**Comment by JoanFM** [comment]
Thank you for reporting the issue. For now we do not want to do the `casting` when creating a `Document` or checking the type of `ID` because we are afraid of the performance impact it could imply.

**Comment by alphinside** [comment]
I see, I think I'm missed that docs. Thanks for clarifying this @JoanFM
