### ISSUE TITLE
It is possible to reduce DocumentArray size

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/docarray#439]
Is it somehow possible to remove unnecessary attributes from root doc (or matches) if they are not used. 
We would like to reduce Jina's response size, which is kind of big. 

We used document.pop to remove embeddings and chunks and kept only matches but it is still quite large (hundreds of kilobytes).

Thank you

**Comment by JoanFM** [comment]
maybe u need to check what attributes from the matches u want to remove. 

Also I am curious. What kind of client do you use with Jina?

**Comment by hanxiao** [comment]
you can add compressions: https://docarray.jina.ai/fundamentals/documentarray/serialization/#from-to-bytes

there is a table there summarizes the size difference

**Comment by tommykoctur** [comment]
Thank @hanxiao , am kind of new to jina 3. http api always return me json with all those attributes which are not needed. How to get rid of those ?

Thanks
