### ISSUE TITLE
A question about document store

### ISSUE THREAD

**Issue by melowYX** [jina-ai/docarray#440]
We know Documents inside a DocumentArray can live in a document store instead of in memory，and DocArray supports multiple storage backends with different search features. We can use `match()` or `find()` to perform approximate nearest neighbour search. 
so, is the implementation of those vector search algorithm done by DocumentArray or by those document store?

**Comment by JoanFM** [comment]
Hello @melowYX ,

In those cases the actual implementation is done by those `backends` and `DocArray` offers a very convenient `Pythonic` Interface.

**Comment by melowYX** [comment]
> 



> Hello @melowYX ,
> 
> In those cases the actual implementation is done by those `backends` and `DocArray` offers a very convenient `Pythonic` Interface.

Thanks for your response
