### ISSUE TITLE
Multi-modal release

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/docarray#444]
Things to do before the public release of new multi-modal narrative.
- [x] implement and release attribute access: https://github.com/jina-ai/docarray/pull/425
- [x] write blog post: https://github.com/jina-ai/internal-tasks/issues/416
  - [ ] release blog post 
- [x] restructure docs
  - [ ] add warning about potential naming collision between built-in properties and custom modalities
- [ ] support `access_path` as `traversal_path` in Executors
- [x] discuss: should data class directly return a Document? @samsja
- [ ] fix #447
- [ ] Q: how does mm play with storage backends?
- [ ] Q: How does mm play with secondary index?

**Comment by JoanFM** [comment]
Step 3 does not imply core right now but Hub Executors
