### ISSUE TITLE
Maybe  a bug  in docarray/array/mixins/plot.py

### ISSUE THREAD

**Issue by yizhangliu** [jina-ai/docarray#455]
In docarray/array/mixins/plot.py, after line 441,  maybe we should add a line:
                          img_per_col = ceil(len(self) / img_per_row)
recalculate  'img_per_col'

**Comment by JoanFM** [comment]
what is the problem observed?

**Comment by yizhangliu** [comment]
Error:  ''Bad image tensor. Try different `image_source` or `channel_axis`"
sprite_img  too  small

**Comment by JoanFM** [comment]
Can u share the exact code snippet that u are trying to run (potentially with some data where the error is reproduced) so that we can investigate?

Thanks!

**Comment by yizhangliu** [comment]
from docarray import DocumentArray
left_da = DocumentArray.from_files('left/*.jpg')       # the dataset contains 6016 images
left_da.plot_image_sprites()


ValueError: Bad image tensor. Try different `image_source` or `channel_axis`

**Comment by JoanFM** [comment]
do you have the images downloaded under `left` folder?

**Comment by yizhangliu** [comment]
Yes, I do.

When I add 'img_per_col = ceil(len(self) / img_per_row)' after line 441,   it's ok.

**Comment by JoanFM** [comment]
So Could you make a PR with a proper test to show that the issue is fixed?

**Comment by JoanFM** [comment]
Hey @yizhangliu,

May you open a PR with ur proposed fix and corresponding tests. The issue has been confirmed.

**Comment by yizhangliu** [comment]
ok.  I have submitted a  PR.
