### ISSUE TITLE
Query filter syntax lead to lower performance that python filtering

### ISSUE THREAD

**Issue by samsja** [jina-ai/docarray#502]
# Query filter syntax lead to lower performance that python filtering

`da.find(query={'text': {'$exists': True}}` is slower than `DocumentArray(d for d in da if d.text)`

```python

import time

from docarray import DocumentArray, Document

num = 10_000
da = DocumentArray(Document(text='lsdkfjsl') for x in range(num)) + DocumentArray(Document(blob=b'lsdkfjsl') for x in range(num))


start = time.time()
print(len(da.find(query={'text': {'$exists': True}})))
print(f'time with find: {time.time() - start}')

start = time.time()
print(len(DocumentArray(d for d in da if d.text)))
print(f'time without find: {time.time() - start}')

```

```shell
10000
time with find: 0.28238487243652344
10000
time without find: 0.015761852264404297
```

reported by @joschkabraun @florian-hoenicke

**Comment by NickOrion21** [comment]
excellent catch, well done

**Comment by alaeddine-13** [comment]
inspection shows that the most bottlenecks are:
* _non_empty_fields method (used when evaluating each document against the condition): 35% of the total script and 62% of find only
* _get_attributes method consumes 10% of find
follow up tickets will be opened to address each bottleneck
