### ISSUE TITLE
Question about DocArray match

### ISSUE THREAD

**Issue by bnuzhanyu** [jina-ai/docarray#525]
We want to build a in-memory and real-time vector search system, and encounter some problems.
1. Is there a way of approximate search for docarray, not precise?
2. Is there realtime insert/delete operation, should I keep track of the mapping from my own item id to doc id? And is the operation  thread safe?

**Comment by JoanFM** [comment]
Hello @bnuzhanyu,

These are the answers to your questions:

1. There is a way to do ANN supported by many of our External Document Stores. You can use for instance `annlite` that provides ANN search.  (https://docarray.jina.ai/advanced/document-store/annlite/)

2. Using the DocArray API you can insert and delete and DocArray takes care of mantaining the mapping between ids and docIDs. 

3. Insert and delete operations have not been designed with thread safety in mind.

**Comment by bnuzhanyu** [comment]
> 
Hi @JoanFM ,
Thanks for your reply. I see annlite but the experiment from jina-document shows the recall@10 is only 0.19, seems not a good result, and we have 100qps of query and about zero insert qps(for about 2M data), which will not take the advantage of annlite. Anyway, I will try that.
Also, I hope the redis result can be updated ^_^

**Comment by JoanFM** [comment]
Hey @bnuzhanyu ,

The benchmark can be trusted to have an idea of the scale of performance expected. We did not have the time and capacity to find a sweet point where the comparision can be made fair. So you would need to change the configuration to reach the desired recall and evaluate there.
