### ISSUE TITLE
Document Filter Question

### ISSUE THREAD

**Issue by bnuzhanyu** [jina-ai/docarray#530]
I want to filter some docs in an executor, and found a solution here:
https://docarray.jina.ai/fundamentals/documentarray/access-elements/#index-by-boolean-mask

There are two questions:
1. Is this the only way to filter document offered by docarray?
2. There seems a wrong description here.
`Note that if the length of the boolean mask is smaller than the length of a DocumentArray, then the remaining part is padded to False.`
It seems the True masked doc will be removed and smaller boolean mask is padding with True. 

Test code :
```python
da = DocumentArray.empty(3)
mask = [True, False] # has same behave with [True, False, True]
del da[mask]
print(len(da))  # got 1
```

**Comment by JoanFM** [comment]
Hey @bnuzhanyu.

For your first question u can see that `find` method accepts filter argument depending on the document store, check this page https://docarray.jina.ai/advanced/document-store/?highlight=filter#feature-summary

For the second question, we are looking into it but it is definitely something wrong either in documentation or in implementation, thanks for reporting the issue

**Comment by bnuzhanyu** [comment]
> Hey @bnuzhanyu.
> 
> For your first question u can see that `find` method accepts filter argument depending on the document store, check this page https://docarray.jina.ai/advanced/document-store/?highlight=filter#feature-summary
> 
> For the second question, we are looking into it but it is definitely something wrong either in documentation or in implementation, thanks for reporting the issue

Thanks, 
for the first question, I just wonder DocumentArray has some method like `docs.filter(lambda d: len(d.text) > 10)`
And I figure it out using python's filter function: `docs = DocumentArray(filter(lambda d: len(d.text) > 10, docs))`

Something really confused is that the document's text field can not set to None.
```python
docs = DocumentArray.empty(3)
docs[0].text = 'abc'
docs[1].text = None
x = DocumentArray(filter(lambda d: d.text is not None, docs))
print(len(x))  # got 3
#though  x = DocumentArray(filter(lambda d: d.text, docs))  will get 2
```
Same for `embedding` field, so I got some problem when I want to filter the doc without embedding, I have to use len(d.embedding) > 0 to make the filter success.
