### ISSUE TITLE
Extend operation on DocumentArray applies change before validation

### ISSUE THREAD

**Issue by Jackmin801** [jina-ai/docarray#544]
```python
from docarray import Document

d = Document(id='Meow')
d.chunks.extend([1, 2, 3])
d.summary()
```

**Expected Behavior**
Throws an error and keeps the Document intact.

**Current Behavior**
Throws an error but modifies the Document.

Reproduction of the bug in colab environment:
https://colab.research.google.com/drive/1n0olEkZ9iKSIvtq1kXbLv5hv59MsSv1L?usp=sharing

**Comment by Jackmin801** [comment]
Maybe bug? Opening again

**Comment by Jackmin801** [comment]
I think it might be worth solving because someone may “Ask forgiveness, not permission” in their code and use a try except case in this scenario. The try except would not work because even though the exception is hit, the damage is done.

Not sure of the tradeoffs though. But if it's as simple as changing an evaluation order then I think it's worth having.

**Comment by JoanFM** [comment]
I guess the code is to reimplement some of the `dunder` methods as `__add__` and all this `Pythonic` ContainerSeqLike objects, but yes it may be worth.

**Comment by samsja** [comment]
It is understandable why this fail, the chunk in just a MutableSequence that can be extend by anything. 

We should do a check, as @Jackmin801 said this is about tradeoff with performance. ( I wish sometime Python could do type checking without overhead).

The code that does that is here : https://github.com/jina-ai/docarray/blob/main/docarray/array/storage/base/seqlike.py#L64-L70

IMO we should check anyway. It is just adding one if statement

**Comment by samsja** [comment]
More in depth look. 

Actually we don't even do extend by bulk, we do a for loop and use append (this is because we need to keep track of the offset2id so this is the only solution). So there is a very minimal overhead to check if the value is a Document or not.

I don't see any reason not to do it @JoanFM

**Comment by JoanFM** [comment]
So let's do this @samsja , it should be quick

**Comment by JoanFM** [comment]
Decided not to pursue. Reasons explained in the PR opened
