### ISSUE TITLE
'AnnLite' object has no attribute '_search_documents'

### ISSUE THREAD

**Issue by oldguard69** [jina-ai/docarray#546]
I'm running the example tutorial "Example of .find with query vector and filter", link: (https://docarray.jina.ai/advanced/document-store/annlite/#example-of-find-with-query-vector-and-filter ), but I got an error as following:

```
[/usr/local/lib/python3.7/dist-packages/docarray/array/storage/annlite/find.py](https://localhost:8080/#) in _find(self, query, limit, only_id, filter, **kwargs)
     38             query = query.reshape(1, -1)
     39 
---> 40         _, match_docs = self._annlite._search_documents(
     41             query, limit=limit, filter=filter or {}, include_metadata=not only_id
     42         )

AttributeError: 'AnnLite' object has no attribute '_search_documents' 
```

I did a search on Google and the Issues tag but find nothing.
I tried installing DocArray with Annlite in both styles but the error still remains:
```pip install docarray[annlite]```
and 
```pip install docarray annlite```

Is there anything I can do to fix this problem?

**Runtime environment**: Google Colab.
P.s: I've already run this example before, and there are no errors.
Thank you for your helps.

**Comment by numb3r3** [comment]
Thanks for pointing it out. This issue is due to the upgrades of annlite. The quick solution is to downgrade annlite package `pip install -U annlite==0.3.11`. And this issue has been fixed by this PR https://github.com/jina-ai/docarray/pull/543, and will be released as a patch.
