### ISSUE TITLE
Add comparison to HuggingeFace Datasets

### ISSUE THREAD

**Issue by tshu-w** [jina-ai/docarray#58]
Hi, wonderful package, Its will be much appreciated if you can add comparison to [huggingface Datasests](https://huggingface.co/docs/datasets/). I find the most attractive features of Datasets are the ability to cache operations and not have to load them all into memory anymore.

**Comment by numb3r3** [comment]
Good points. the caching and streaming loading supports are absolutely in our plan. Please keep tracking and play it around. We always appreciate any comments from our community.

**Comment by hanxiao** [comment]
Thanks for your attention.

There are a couple of features that we will release soon to allow big data loading with constant memory consumption.

But in general, I want to clarify that DocArray is designed to be **a data type in transit**, which means its IO interfaces and designs are focused on thread-to-thread, process-to-process, microservice-to-microservice network communication. This is as opposed to alternatives, e.g. HF datasets, which focus on *data at rest*: inactive data subject to very occasional changes (e.g. you rarely change the content in the training data).

The data in transit part will become much clear when Jina 3.0 is out (expect in Feb.)

**Comment by tshu-w** [comment]
@hanxiao Thank you for your replies, I will keep my eyes on it..

**Comment by hanxiao** [comment]
fyi, added to docs: https://docarray.jina.ai/get-started/what-is/#to-huggingface-datasets
