### ISSUE TITLE
Bug: document stores disappeared in api reference

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/docarray#580]
Despite being listed in the `.rst`, most document stores do not appear in the table; only in memory and sqlite are visible

![Image](https://user-images.githubusercontent.com/44071807/193079752-9eb9c138-435b-4cf9-afce-629ec48d5105.png)

![Image](https://user-images.githubusercontent.com/44071807/193079775-f32e774e-9bbe-405e-a31b-966eec23ac0f.png)

**Comment by JoanFM** [comment]
Does this happen when building documentation locally?

**Comment by hanxiao** [comment]
check build log
