### ISSUE TITLE
Add args for all load_uri_to_video_tensor

### ISSUE THREAD

**Issue by TEChopra1000** [jina-ai/docarray#656]
Request to make the arguments for the functions used to load data via `load_uri_to_video_tensor` function available.

For example, `load_uri_to_video_tensor`'s `av` library provides a timeout argument that in some cases, will prevent the program from hanging. Being able to access that parameter would be helpful. Reference: https://pyav.org/docs/develop/api/_globals.html

**Comment by JoanFM** [comment]
Hey @TEChopra1000,

Could you provide a PR where these parameters are exposed as keyword arguments?
