### ISSUE TITLE
AttributeError: d.embed_feature_hashing() in the README 10-liner  text matching example

### ISSUE THREAD

**Issue by WeissZucker** [jina-ai/docarray#75]

**Comment by numb3r3** [comment]
Thanks for reporting. could you provide more detailed exception message and the `docarray` version you are using?  It help me to identify the issue. Thanks

**Comment by WeissZucker** [comment]
Oh sorry I was focusing on the examples and didn't realize docarray has to be installed separately with jina. Now I installed docarray and it runs without any problem. 👍
