### ISSUE TITLE
Support JPG for convert_image_tensor_to_uri

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/docarray#98]
`convert_image_tensor_to_uri` is useful when you respond Documents to a frontend. The data uri can directly used to visualize the document.
However, sending PNGs is not acceptable since it leads to serious network issues. Moreover is much more memory efficient to store jpgs in an indexer than PNGs.
Please let `convert_image_tensor_to_uri` support `JPEG` as well.
Introduce two parameters:
`format`(default=png) and `quality` (default=0.9)

**Comment by JoanFM** [comment]
This needs to go if needed in `docarray`

**Comment by JoanFM** [comment]
Oh sorry, @CatStark this does not belong in core
